#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit checks..."

npx lint-staged

RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "Pre-commit checks failed."
  exit $RESULT
fi

echo "Pre-commit checks passed."s